exclude: ^vendor/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: name-tests-test
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.1.1
    hooks:
    -   id: clang-format
        args: [-i, --style=file]
    -   id: clang-tidy
        args: [-checks=*, -warnings-as-errors*]
-   repo: https://github.com/detailyang/pre-commit-shell.git
    rev: 1.0.5
    hooks:
    -   id: shell-lint
